import { PERMITTED_LANGUAGES } from "@/utils/content";
import type { PolicyCountry } from "./types";

export const POLICY_COUNTRIES: PolicyCountry[] = [
  {
    slug: "bolivia",
    name_en: "Bolivia",
    name_es: "Bolivia",
    name_pt: "Bolívia",
    desc_en:
      "Minamata ratification and the existence of a National Action Plan, combined with the FOFIM financing mechanism for sustainable mining alternatives, give **Bolivia** a more complete policy toolkit than other countries. Its formal enforcement architecture, particularly restrictions and sanctions authority, performs comparably to **Brazil** and **Colombia** on paper. However, **Bolivia** is the only country to not reach a perfect score in the category of legal definitions. Its legal framework only incorporates vague ASM definitions that fail to distinguish small-scale from mechanized mining and incomplete regulation in protected and Indigenous areas.\n\nThe Bolivian mining registry is not publicly available, which negatively affects the country’s score on monitoring and transparency across different sections. In addition,  **Bolivia** doesn’t count with structured policies for formalization of ASM and mercury use reduction. Although the country has enacted legislation regulating mercury use, it lacks established traceability systems.",
    desc_es:
      "La ratificación de la Convención de Minamata y la existencia de un Plan de Acción Nacional, combinadas con el mecanismo de financiación FOFIM para alternativas mineras sostenibles, dotan a **Bolivia** de un conjunto de herramientas políticas más completo que el de otros países. Su arquitectura formal de cumplimiento, en particular la autoridad en materia de restricciones y sanciones tiene un rendimiento comparable al de **Brasil** y **Colombia** sobre el papel. Sin embargo, **Bolivia** es el único país que no alcanza una puntuación perfecta en la categoría de definiciones legales. Su marco jurídico solo incorpora definiciones vagas de la minería artesanal y de pequeña escala (MAPE) que no distinguen entre la minería a pequeña escala y la mecanizada, y una regulación incompleta en las áreas protegidas e indígenas.\n\nEl registro minero boliviano no es de acceso público, lo que afecta negativamente a la puntuación del país en materia de seguimiento y transparencia en diferentes apartados. Además, **Bolivia** no cuenta con políticas estructuradas para la formalización de la MAPE y la reducción del uso de mercurio. Aunque el país ha promulgado legislación que regula el uso del mercurio, carece de sistemas de trazabilidad establecidos.",
    desc_pt:
      "A ratificação da Convenção de Minamata e a existência de um Plano de Ação Nacional, combinadas com o mecanismo de financiamento FOFIM para alternativas de mineração sustentável, conferem à **Bolívia** um conjunto de ferramentas políticas mais completo do que o de outros países. Sua estrutura formal de fiscalização, particularmente no que diz respeito a restrições e sanções, apresenta desempenho comparável ao do **Brasil** e da **Colômbia** no papel. No entanto, a **Bolívia** é o único país que não atingiu nota máxima na categoria de definições legais. Seu marco legal incorpora apenas definições vagas de mineração artesanal e de pequena escala (ASM), que não distinguem a mineração de pequena escala da mecanizada, além de regulamentação incompleta em áreas protegidas e indígenas.\n\nO cadastro de mineração boliviano não está disponível ao público, o que afeta negativamente a pontuação do país em monitoramento e transparência em diferentes seções. Além disso, a **Bolívia** não conta com políticas estruturadas para a formalização da ASM e a redução do uso de mercúrio. Embora o país tenha promulgado legislação regulamentando o uso de mercúrio, carece de sistemas de rastreabilidade estabelecidos.",
  },
  {
    slug: "brazil",
    name_en: "Brazil",
    name_es: "Brasil",
    name_pt: "Brasil",
    desc_en:
      '**Brazil** performs well on gold supply chain regulation and transparency. Gold transaction disclosure is mandatory, and in 2023 the government launched the Electronic Fiscal Invoice for Gold (NF-e Ouro) to improve traceability in gold trade.\n\n**Brazil** receives the highest score for support to responsible mining activities. Through the national Gold Without Mercury program, the Ministry of Mines and Energy promotes sector formalization, mercury-free technologies, and improved accountability across gold supply chains.\n\n**Brazil** also leads on monitoring systems. The country possesses advanced governmental satellite monitoring systems, operated primarily by the National Institute for Space Research (INPE), the Management and Operational Center of the Amazon Protection System (CENSIPAM), and the Brazilian Institute of Environment and Renewable Natural Resources (IBAMA), which allow for the detection and monitoring of the expansion of mining areas, including gold mining in the Legal Amazon. These systems, available to all public civil servants through the BrasilMAIS platform, use medium-resolution satellite images to detect areas of altered forest cover, classifying them into categories such as "deforestation," "mining," "selective logging," and "degradation."',
    desc_es:
      "**Brasil** obtiene buenos resultados en materia de regulación y transparencia de la cadena de suministro del oro. La divulgación de las transacciones de oro es obligatoria y, en 2023, el Gobierno puso en marcha la Factura Fiscal Electrónica para el Oro (NF-e Ouro) con el fin de mejorar la trazabilidad en el comercio del oro.\n\n**Brasil** obtiene la puntuación más alta en apoyo a las actividades mineras responsables. A través del programa nacional «Oro sin Mercurio», el Ministerio de Minas y Energía promueve la formalización del sector, las tecnologías sin mercurio y una mayor rendición de cuentas en todas las cadenas de suministro del oro.\n\n**Brasil** también es líder en sistemas de monitoreo. El país cuenta con avanzados sistemas gubernamentales de monitoreo por satélite, operados principalmente por el Instituto Nacional de Investigaciones Espaciales (INPE), el Centro de Gestión y Operaciones del Sistema de Protección de la Amazonía (CENSIPAM) y el Instituto Brasileño del Medio Ambiente y de los Recursos Naturales Renovables (IBAMA), que permiten detectar y monitorear la expansión de las áreas mineras, incluida la minería de oro en la Amazonía Legal. Estos sistemas, a disposición de todos los funcionarios públicos a través de la plataforma BrasilMAIS, utilizan imágenes satelitales de resolución media para detectar áreas de cobertura forestal alterada, clasificándolas en categorías como «deforestación», «minería», «tala selectiva» y «degradación».",
    desc_pt:
      "O **Brasil** apresenta bom desempenho em regulamentação e transparência da cadeia de suprimentos de ouro. A divulgação de transações de ouro é obrigatória e, em 2023, o governo lançou a Nota Fiscal Eletrônica de Ouro (NF-e Ouro) para melhorar a rastreabilidade no comércio de ouro.\n\nO **Brasil** recebe a pontuação mais alta pelo apoio a atividades de mineração responsável. Por meio do programa nacional Ouro Sem Mercúrio, o Ministério de Minas e Energia promove a formalização do setor, tecnologias sem mercúrio e maior prestação de contas em todas as cadeias de abastecimento de ouro.\n\nO **Brasil** também é líder em sistemas de monitoramento. O país possui avançados sistemas governamentais de monitoramento por satélite, operados principalmente pelo Instituto Nacional de Pesquisas Espaciais (INPE), pelo Centro de Gestão e Operações do Sistema de Proteção da Amazônia (CENSIPAM) e pelo Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis (IBAMA), que permitem a detecção e o monitoramento da expansão de áreas de mineração, incluindo a mineração de ouro na Amazônia Legal. Esses sistemas, disponíveis para todos os servidores públicos por meio da plataforma BrasilMAIS, utilizam imagens de satélite de média resolução para detectar áreas de alteração da cobertura florestal, classificando-as em categorias como “desmatamento”, “mineração”, “exploração madeireira seletiva” e “degradação”.",
  },
  {
    slug: "colombia",
    name_en: "Colombia",
    name_es: "Colombia",
    name_pt: "Colômbia",
    desc_en:
      "**Colombia** is the only country to achieve a perfect score on mercury regulation, through restrictions on mercury commercialization and use in ASM, the establishment of a national user registry (Registro de Usuarios de Mercurio) and full compliance with the Minamata Convention, highlighting the incorporation of intersectional strategies and Amazon-specific goals into its National Action Plan.\n\nOn machinery regulation, **Colombia** stands out for combining legal limits on machinery types in ASM with proactive monitoring requirements mandating that operators equip heavy equipment with GPS or similar tracking devices.",
    desc_es:
      "**Colombia** es el único país que ha obtenido una puntuación perfecta en materia de regulación del mercurio, gracias a las restricciones a la comercialización y el uso del mercurio en la minería artesanal y de pequeña escala (MAPE), la creación de un registro nacional de usuarios (Registro de Usuarios de Mercurio) y el pleno cumplimiento de la Convención de Minamata, destacando la incorporación de estrategias intersectoriales y objetivos específicos para la Amazonía en su Plan de Acción Nacional.\n\nEn cuanto a la regulación de la maquinaria, **Colombia** destaca por combinar límites legales sobre los tipos de maquinaria en la MAPE con requisitos de seguimiento proactivos que obligan a los operadores a equipar la maquinaria pesada con GPS o dispositivos de rastreo similares.",
    desc_pt:
      "A **Colômbia** é o único país a obter nota máxima na regulamentação do mercúrio, por meio de restrições à comercialização e ao uso de mercúrio na mineração artesanal e de pequena escala (ASM), da criação de um registro nacional de usuários (Registro de Usuários de Mercúrio) e do cumprimento integral da Convenção de Minamata, destacando a incorporação de estratégias intersetoriais e metas específicas para a Amazônia em seu Plano de Ação Nacional.\n\nNo que diz respeito à regulamentação de máquinas, a **Colômbia** se destaca por combinar limites legais para tipos de máquinas na ASM com requisitos de monitoramento proativos que exigem que os operadores equipem máquinas pesadas com GPS ou dispositivos de rastreamento similares.",
  },
  {
    slug: "ecuador",
    name_en: "Ecuador",
    name_es: "Ecuador",
    name_pt: "Equador",
    desc_en:
      "The country stands out on machinery regulation, as the Ministry of Transport and Public Works regulates machinery use and maintains a national registry of miners operating equipment and accessories, scoring higher than **Peru** and **Brazil** in this aspect. **Ecuador’s** legal framework also presents public participation - including a special consultation process with indigenous communities - as a constitutional right, and counts with State-backed financing mechanisms that promote alternatives to unsustainable ASM gold mining, through a credit line given by the national bank (BANECUADOR).\n\nMeanwhile, **Ecuador** scored zero on the monitoring system criteria, as the government does not count with any official monitoring systems to track illegal gold mining activities and the use of mercury.",
    desc_es:
      "El país destaca en materia de regulación de maquinaria, ya que el Ministerio de Transporte y Obras Públicas regula el uso de la maquinaria y mantiene un registro nacional de equipos y accesorios utilizados por los mineros, obteniendo una puntuación superior a la de **Perú** y **Brasil** en este aspecto. El marco legal de **Ecuador** también establece la participación pública —incluido un proceso de consulta especial con las comunidades indígenas— como un derecho constitucional, y cuenta con mecanismos de financiación respaldados por el Estado que promueven alternativas a la minería de oro artesanal y de pequeña escala (MAPE) insostenible, a través de una línea de crédito otorgada por el banco nacional (BANECUADOR).\n\nPor su parte, **Ecuador** obtuvo una puntuación de cero en los criterios del sistema de seguimiento, ya que el Gobierno no cuenta con ningún sistema oficial de seguimiento para controlar las actividades de minería aurífera ilegal y el uso de mercurio.",
    desc_pt:
      "O país se destaca na regulamentação de maquinário, já que o Ministério dos Transportes e Obras Públicas regula o uso de maquinário e mantém um registro nacional de equipamentos e acessórios operados por mineradores, obtendo pontuação superior à do **Peru** e do **Brasil** nesse aspecto. O marco legal do **Equador** também apresenta a participação pública — incluindo um processo especial de consulta às comunidades indígenas — como um direito constitucional, e conta com mecanismos de financiamento apoiados pelo Estado que promovem alternativas à mineração de ouro ASM insustentável, por meio de uma linha de crédito concedida pelo banco nacional (BANECUADOR).\n\nEnquanto isso, o **Equador** obteve nota zero nos critérios de sistema de monitoramento, já que o governo não conta com nenhum sistema oficial de monitoramento para rastrear atividades ilegais de mineração de ouro e o uso de mercúrio.",
  },
  {
    slug: "guyana",
    name_en: "Guyana",
    name_es: "Guyana",
    name_pt: "Guiana",
    desc_en:
      "**Guyana** has developed a solid legal framework for the ASM sector, anchored in the Mining Act 1989 and the Mercury Act 2020, and has actively partnered with international programs to strengthen mercury reduction and sector formalization.\n\n**Guyana** stands out for its mercury governance framework which prohibits the use of mercury in open-system ASM operations and establishes a licensing regime for imports with annual caps. **Guyana** also has procedures in place for the seizure and controlled handling of confiscated mercury.\n\nOn gold supply chain regulation, **Guyana** has established mandatory transaction disclosure through the **Guyana** Gold Board. However, small-scale mining tenure data is not publicly available, limiting the feasibility of a comprehensive digital traceability system tracking gold from extraction to final sale. **Guyana** also lacks dedicated licensing or registry systems for heavy mining equipment.",
    desc_es:
      "**Guyana** ha desarrollado un sólido marco jurídico para el sector de la MAPE, basado en la Ley de Minería de 1989 y la Ley del Mercurio de 2020, y ha colaborado activamente con programas internacionales para reforzar la reducción del mercurio y la formalización del sector.\n\n**Guyana** destaca por su marco de gobernanza del mercurio, que prohíbe su uso en las operaciones de MAPE a cielo abierto y establece un régimen de licencias para las importaciones con límites anuales. **Guyana** también cuenta con procedimientos para la incautación y la gestión controlada del mercurio confiscado.\n\nEn cuanto a la regulación de la cadena de suministro del oro, **Guyana** ha establecido la divulgación obligatoria de las transacciones a través de la Junta del Oro de **Guyana**. Sin embargo, los datos sobre los derechos de tenencia de la minería a pequeña escala no están disponibles públicamente, lo que limita la viabilidad de un sistema digital de trazabilidad integral que permita seguir el recorrido del oro desde su extracción hasta su venta final. **Guyana** tampoco cuenta con sistemas específicos de concesión de licencias o de registro para la maquinaria pesada de minería.",
    desc_pt:
      "A **Guiana** desenvolveu um sólido marco legal para o setor de ASM, ancorado na Lei de Mineração de 1989 e na Lei do Mercúrio de 2020, e tem colaborado ativamente com programas internacionais para fortalecer a redução do uso de mercúrio e a formalização do setor.\n\nA **Guiana** se destaca por seu quadro de governança do mercúrio, que proíbe o uso de mercúrio em operações de ASM em sistema aberto e estabelece um regime de licenciamento para importações com limites anuais. A **Guiana** também possui procedimentos em vigor para a apreensão e o manuseio controlado do mercúrio confiscado.\n\nNo que diz respeito à regulamentação da cadeia de abastecimento de ouro, a **Guiana** estabeleceu a divulgação obrigatória de transações por meio do Conselho de Ouro da **Guiana**. No entanto, os dados sobre concessões de mineração de pequena escala não estão disponíveis publicamente, limitando a viabilidade de um sistema digital abrangente de rastreabilidade que acompanhe o ouro desde a extração até a venda final. A **Guiana** também carece de sistemas dedicados de licenciamento ou registro para equipamentos pesados de mineração.",
  },
  {
    slug: "peru",
    name_en: "Peru",
    name_es: "Perú",
    name_pt: "Peru",
    desc_en:
      "**Peru** stands out across the region on gold supply chain transparency as it requires formal registration of all actors in the ASM gold supply chain (miners, traders, and exporters) and provides geospatially compatible data on ASM titles and zones through the GEOCATMIN portal. Transaction reporting in the country is mandatory, and miners, traders, and processors must register and report operations via RECPO and RCMPM to the Ministry of Energy and Mines.\n\n**Peru** is the only country with a perfect score on public participation, with official channels for civil society to report illegal activity and protocols to support victims of illegal mining. ASM programs include targeted support for underrepresented groups, such as the National Gender Plan (2023–2025), which promotes the participation of women, Indigenous peoples, and traditional communities.",
    desc_es:
      "**Perú** destaca en toda la región por la transparencia de la cadena de suministro del oro, ya que exige el registro formal de todos los actores de la cadena de suministro de la MAPE (mineros, comerciantes y exportadores) y proporciona datos geoespaciales compatibles sobre los títulos y zonas de la MAPE a través del portal GEOCATMIN. La notificación de transacciones en el país es obligatoria, y los mineros, comerciantes y procesadores deben registrarse e informar de sus operaciones a través de RECPO y RCMPM al Ministerio de Energía y Minas.\n\n**Perú** es el único país con una puntuación perfecta en materia de participación pública, con canales oficiales para que la sociedad civil denuncie actividades ilegales y protocolos de apoyo a las víctimas de la minería ilegal. Los programas de MAPE incluyen apoyo específico para grupos infrarrepresentados, como el Plan Nacional de Género (2023-2025), que promueve la participación de las mujeres, los pueblos indígenas y las comunidades tradicionales.",
    desc_pt:
      "O **Peru** se destaca na região na seção “Transparência da Cadeia de Suprimentos de Ouro”, pois exige o registro formal de todos os atores na cadeia de suprimentos de ouro da ASM (garimpeiros, comerciantes e exportadores) e fornece dados geoespaciais compatíveis sobre títulos e zonas de ASM por meio do portal GEOCATMIN. A comunicação de transações no país é obrigatória, e garimpeiros, comerciantes e processadores devem registrar e comunicar suas operações via RECPO e RCMPM ao Ministério de Energia e Minas.\n\nO **Peru** é o único país com nota máxima em participação pública, com canais oficiais para a sociedade civil denunciar atividades ilegais e protocolos para apoiar vítimas da mineração ilegal. Os programas de ASM incluem apoio direcionado a grupos sub-representações, como o Plano Nacional de Gênero (2023–2025), que promove a participação de mulheres, povos indígenas e comunidades tradicionais.",
  },
  {
    slug: "venezuela",
    name_en: "Venezuela",
    name_es: "Venezuela",
    name_pt: "Venezuela",
    desc_en:
      "While legislation exists across most governance dimensions, the Venezuelan government’s role in mining is characterised by opacity and limited accountability. In fact, because **Venezuela’s** gold sector is subject to a state monopoly,  all production is legally required to be sold to the Central Bank. While this formally centralises oversight, the Single Mining Registry (RUM) is not publicly accessible, concession and transaction data are withheld on national security grounds, affecting transparency.\n\nAlone amongst Amazonian countries, **Venezuela** has not ratified the Minamata Convention on Mercury and therefore lacks a National Action Plan, a formal initial assessment, or any mercury reduction strategy. **Venezuela** received a score of zero on government-led monitoring systems, as the country does not have any official satellite monitoring programme for ASM and its impacts.",
    desc_es:
      "Si bien existe legislación en la mayoría de las dimensiones de gobernanza, el papel del Gobierno venezolano en la minería se caracteriza por la opacidad y una rendición de cuentas limitada. De hecho, dado que el sector aurífero de **Venezuela** está sujeto a un monopolio estatal, toda la producción está obligada por ley a venderse al Banco Central. Si bien esto centraliza formalmente la supervisión, el Registro Único de Minería (RUM) no es de acceso público, y los datos sobre concesiones y transacciones se ocultan por motivos de seguridad nacional, lo que afecta a la transparencia.\n\n**Venezuela** es el único país amazónico que no ha ratificado la Convención de Minamata sobre el Mercurio y, por lo tanto, carece de un Plan de Acción Nacional, una evaluación inicial formal o cualquier estrategia de reducción del mercurio. **Venezuela** obtuvo una puntuación de cero en los sistemas de seguimiento dirigidos por el gobierno, ya que el país no cuenta con ningún programa oficial de seguimiento por satélite de la minería artesanal y de pequeña escala (MAPE) y sus impactos.",
    desc_pt:
      "Embora exista legislação na maioria das dimensões de governança, o papel do governo venezuelano na mineração é caracterizado por opacidade e responsabilização limitada. De fato, como o setor de ouro da **Venezuela** está sujeito a um monopólio estatal, toda a produção é legalmente obrigada a ser vendida ao Banco Central. Embora isso centralize formalmente a supervisão, o Registro Único de Mineração (RUM) não é acessível ao público, e os dados de concessões e transações são retidos por motivos de segurança nacional, afetando a transparência.\n\nÚnico entre os países amazônicos, a **Venezuela** não ratificou a Convenção de Minamata sobre o Mercúrio e, portanto, carece de um Plano de Ação Nacional, de uma avaliação inicial formal ou de qualquer estratégia de redução do mercúrio. A **Venezuela** recebeu nota zero em sistemas de monitoramento liderados pelo governo, já que o país não possui nenhum programa oficial de monitoramento por satélite para a mineração artesanal e de pequena escala (ASM) e seus impactos.",
  },
  {
    slug: "suriname",
    name_en: "Suriname",
    name_es: "Suriname",
    name_pt: "Suriname",
    desc_en:
      "The legal framework in **Suriname** consists of a Mining Decree from 1986 that contains no specific provisions for the ASM sector. The absence of a publicly accessible mining cadastre and the lack of binding court decisions on mining-related crimes further limit accountability across the sector.\n\n**Suriname** is the only country to receive a score of zero on mercury regulation despite its Minamata ratification. The national legal framework contains no provisions specifically regulating mercury import, sale, or use in the ASM sector. All mercury currently used in mining enters illicitly, as no authorised imports have been recorded since 2003, and no enforcement mechanism exists to target its distribution or use in the field.\n\n**Suriname’s** relatively high score on Mining policies can be explained by its international policy commitments under the Minamata convention and active collaboration with international programmes. The national biodiversity strategy of the country also explicitly identifies small-scale gold mining as a primary driver of biodiversity loss and integrates ecosystem restoration targets.",
    desc_es:
      "El marco jurídico de **Surinam** consiste en un Decreto de Minería de 1986 que no contiene disposiciones específicas para el sector de la MAPE. La ausencia de un catastro minero de acceso público y la falta de sentencias judiciales vinculantes sobre delitos relacionados con la minería limitan aún más la rendición de cuentas en todo el sector.\n\n**Surinam** es el único país que ha recibido una puntuación de cero en materia de regulación del mercurio a pesar de su ratificación del Convenio de Minamata. El marco jurídico nacional no contiene disposiciones que regulen específicamente la importación, la venta o el uso de mercurio en el sector de la MAPE. Todo el mercurio que se utiliza actualmente en la minería entra de forma ilícita, ya que no se han registrado importaciones autorizadas desde 2003 y no existe ningún mecanismo de aplicación de la ley que controle su distribución o uso sobre el terreno.\n\nLa puntuación relativamente alta de **Surinam** en materia de políticas mineras puede explicarse por sus compromisos políticos internacionales en virtud de la Convención de Minamata y su colaboración activa con programas internacionales. La estrategia nacional de biodiversidad del país también identifica explícitamente la minería aurífera a pequeña escala como uno de los principales factores de la pérdida de biodiversidad e integra objetivos de restauración de los ecosistemas.",
    desc_pt:
      "O marco legal no **Suriname** consiste em um Decreto de Mineração de 1986 que não contém disposições específicas para o setor de ASM. A ausência de um cadastro de mineração acessível ao público e a falta de decisões judiciais vinculativas sobre crimes relacionados à mineração limitam ainda mais a prestação de contas em todo o setor.\n\nO **Suriname** é o único país a receber nota zero em regulamentação do mercúrio, apesar de ter ratificado a Convenção de Minamata. O marco jurídico nacional não contém disposições que regulamentem especificamente a importação, venda ou uso de mercúrio no setor de ASM. Todo o mercúrio atualmente utilizado na mineração entra de forma ilícita, já que não foram registradas importações autorizadas desde 2003 e não existe nenhum mecanismo de fiscalização para coibir sua distribuição ou uso no campo.\n\nA pontuação relativamente alta do **Suriname** em políticas de mineração pode ser explicada por seus compromissos políticos internacionais no âmbito da Convenção de Minamata e pela colaboração ativa com programas internacionais. A estratégia nacional de biodiversidade do país também identifica explicitamente a mineração de ouro em pequena escala como um dos principais fatores da perda de biodiversidade e integra metas de restauração de ecossistemas.",
  },
];

export const POLICY_COUNTRY_SLUGS = POLICY_COUNTRIES.map((d) => d.slug);
export type PERMITTED_POLICY_COUNTRY_SLUGS =
  (typeof POLICY_COUNTRY_SLUGS)[number];

const findCountry = (name_en: string) =>
  POLICY_COUNTRIES.find((c) => c.name_en === name_en);

export const getPolicyCountryDescriptionLocalized = (
  name_en: string,
  lang: PERMITTED_LANGUAGES,
) => findCountry(name_en)?.[`desc_${lang}`] ?? "";
